In [1]:
# uebung numpy: Index, Slice and Reshape
# convert list to array
from numpy import array
date = [1,2,3,4,5]

In [2]:
print(type(date))

<class 'list'>


In [3]:
date = array(date)
print(date)
print(type(date))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
data = [[1,2,3],[4,5,6]]
print(data)
print(type(data))
data = array(data)
print(data)
print(type(data))

[[1, 2, 3], [4, 5, 6]]
<class 'list'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [5]:
data = array([1,2,3,4])
print(data[0])

1


In [10]:
data = array([[1,2,3,4],[5,6,7,8]])
print(data[0,3])
print(data[0][3])
print(data[0,])
print(data[0,:])
print(data[0][:])

4
4
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [14]:
print(data[:])
print(data[:][1])
print(data[:,1])

[[1 2 3 4]
 [5 6 7 8]]
[5 6 7 8]
[2 6]


In [16]:
data = array([[1,2,3,4],[5,6,7,8],[0,0,0,0]])
x,y = data[:,:-1],data[:,-1]
print(x)
print(y)
x1, y1 = data[:2,:],data[2:,:]
print(x1)
print(y1)

[[1 2 3]
 [5 6 7]
 [0 0 0]]
[4 8 0]
[[1 2 3 4]
 [5 6 7 8]]
[[0 0 0 0]]


In [19]:
# shape
data = array([1,2,3,4])
print(data.shape)
print(type(data.shape))

(4,)
<class 'tuple'>


In [2]:
data = array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(data)
print(data.shape)
data1 = data.reshape(1,-1)#缺省用-1代替
print(data1)
#data2 = data.reshape(8,1)
#print(data2)
data3 = data.reshape(data.shape[0],data.shape[1]//2,2)
#层 长 宽 
print(data3)
print(data3[0,0,0])
print(data3[0,0,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
1
2
